--- Makefile	2023-07-17 14:40:23
+++ Makefileadj	2023-07-17 14:40:02
@@ -12,19 +12,19 @@
 	@echo "-- on low RAM systems use 'apt install cpanminus' and then 'make CPAN=cpanm requirements'"
 
 requirements::
-	sudo apt install libexpat-dev libcurses-perl libncurses5-dev libreadline-dev
-	sudo ${CPAN} File::Which IO::Zlib Time::HiRes Device::SerialPort XML::Simple JSON IO::Termios Term::ReadLine::Gnu Linux::Termios2 Algorithm::BinPack::2D 
-	sudo apt install libgd-perl ser2net socat slic3r
-	sudo apt install yagv
+	apt install -y libexpat-dev libcurses-perl libncurses5-dev libreadline-dev
+	${CPAN} File::Which IO::Zlib Time::HiRes Device::SerialPort XML::Simple JSON IO::Termios Term::ReadLine::Gnu Linux::Termios2 Algorithm::BinPack::2D 
+	apt install -y libgd-perl ser2net socat slic3r
+	apt install -y yagv
 
 install::
-	sudo cp ${CMD} ${DEST_BIN}/
+	cp ${CMD} ${DEST_BIN}/
 	mkdir -p ${HOME}/.config/${NICK}; cd ${HOME}/.config/${NICK}; mkdir -p printer macro macro/filament slicer gconsole gconsole/commands 
-	sudo mkdir -p ${DEST_SHARE}/${NICK}
-	cd settings; tar cf - printer/*.ini macro/*.ini macro/filament/*.ini slicer/*.json slicer/*/base.ini slicer/*/map.ini slicer/*/*.def.json slicer/*/strict.ini gconsole | (cd ${DEST_SHARE}/${NICK}/; sudo tar xf -)
+	mkdir -p ${DEST_SHARE}/${NICK}
+	cd settings; tar cf - printer/*.ini macro/*.ini macro/filament/*.ini slicer/*.json slicer/*/base.ini slicer/*/map.ini slicer/*/*.def.json slicer/*/strict.ini gconsole | (cd ${DEST_SHARE}/${NICK}/; tar xf -)
 
 deinstall::
-	sudo rm -f ${DEST_BIN}/${CMD}
+	rm -f ${DEST_BIN}/${CMD}
 
 # ---------------------------------------------------------------------------------------------------------------
 # -- developer(s) only:
