---
name: Workflow "cadquery_build"

on:
  workflow_dispatch:

permissions:
  packages: write
  contents: read

jobs:
  init:
    uses: PhilippAuch/workflows/.github/workflows/init.yaml@main

  build:
    uses: PhilippAuch/workflows/.github/workflows/buildDocker.yaml@main
    permissions:
      packages: write
      contents: read
    with:
      subfolder: './build_conda_package/'
      imageNameAddon: '-build_conda_package'
      platforms: 'linux/amd64,linux/arm64/v8'
